[package]
name = "rustedbytes-tris"
version = "0.1.0"
edition = "2024"

[dependencies]
minifb = "0.28.0"
rand = "0.9.1"
raqote = "0.8.5"

[target.'cfg(windows)'.dependencies]
temp-file = "0.1.9"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"